answers = {
    "bis" : "hasta",
    "für" : "para",
    "ohne" : "sin",
    "durch" : "atraves",
    "um" : "a las",
    "gegen" : "contra",
    "an" : "fechas",
    "in" : "en/hacia",
    "über" : "sobre",
    "auf" : "encima",
    "unter" : "abajo",
    "vor" : "adelante",
    "hinter" : "atras",
    "neben" : "junto",
    "zwishen" : "entre",
    "von" : "propiedad",
    "aus" : "origen/material",
    "nach" : "hacia",
    "zu" : "hacia",
    "mit" : "con",
    "bei" : "con/para/por",
    "ab" : "a partir de",
    "seit" : "desde",
    "ausserchen" : "excepto",
    "gengenünber" : "enfrente"
}